### PR TITLE
Fix wait_for_db method

### LINKED ISSUE #97: Mariadb servicename is hardwired in docker image
-------------------------------
    BUG REPORT INFORMATION
-------------------------------

**Description**

I tried to use bitnami Laravel in combination with an existing (non bitnami) dockerized sql service. for reasons this sql service was named mysql in the docker-compose file rather than `mariadb`. Turns out if you modify the docker-compose file only slightly to use this different name, it will not start because there is a shell script which hardcodedly expects the database hostname to be  'mariadb'. See the following code line:

https://github.com/bitnami/bitnami-docker-laravel/blob/master/5/ol-7/rootfs/app-entrypoint.sh#L20

The shell script should rather use the provided hostname in the environment settings  (https://github.com/bitnami/bitnami-docker-laravel/blob/master/docker-compose.yml#L18) than rely on knowledge about what is inside docker-compose.yml.

**Steps to reproduce the issue:**

1. Rename `mariadb' in the docker-compose.yml to anything else. Also modify the hostname on https://github.com/bitnami/bitnami-docker-laravel/blob/master/docker-compose.yml#L18 to reflect the fact that you picked a different hostname for the database.
2. docker-compose up
3. you will see that the database connection will not establish, despite the hostname environment variable being set correctly.

**Describe the results you received:**

the database connection will timeout and the machine will be closed.

**Describe the results you expected:**

I expect any shell script inside the docker to use this environment variable rather than the docker compose service name https://github.com/bitnami/bitnami-docker-laravel/blob/master/docker-compose.yml#L18

**Version**

- Output of `docker version`:

```
Client:
 Version:	18.03.0-ce
 API version:	1.37
 Go version:	go1.9.4
 Git commit:	0520e24
 Built:	Wed Mar 21 23:06:22 2018
 OS/Arch:	darwin/amd64
 Experimental:	false
 Orchestrator:	swarm

Server:
 Engine:
  Version:	18.03.0-ce
  API version:	1.37 (minimum version 1.12)
  Go version:	go1.9.4
  Git commit:	0520e24
  Built:	Wed Mar 21 23:14:32 2018
  OS/Arch:	linux/amd64
  Experimental:	true
```

- Output of `docker info`:

```
Containers: 3
 Running: 2
 Paused: 0
 Stopped: 1
Images: 51
Server Version: 18.03.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfd04396dc68220d1cecbe686a6cc3aa5ce3667c
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.87-linuxkit-aufs
Operating System: Docker for Mac
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.952GiB
Name: linuxkit-025000000001
ID: PUVC:WF45:UXCU:CESK:6RMJ:GAGT:K4DP:2OJX:SJPC:D7FY:FPND:2VQP
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 51
 Goroutines: 76
 System Time: 2018-12-28T10:37:20.5413798Z
 EventsListeners: 4
HTTP Proxy: docker.for.mac.http.internal:3128
HTTPS Proxy: docker.for.mac.http.internal:3129
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.20.1, build 5d8c71b
docker-py version: 3.1.4
CPython version: 3.6.4
OpenSSL version: OpenSSL 1.0.2n  7 Dec 2017
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

### PR DESCRIPTION
**Pull request by andresbono**
This PR fixes #97.

### CODE REVIEW

**Comment by RokSiEu** [comment]
@andresbono any reason why this PR didn't make into debian-10 ? 
https://github.com/bitnami/bitnami-docker-laravel/blob/master/8/debian-10/rootfs/app-entrypoint.sh

**Comment by dani8art** [comment]
Hi @RokSiEu, when this PR was merged those versions didn't exist but the changes were propagated to the new versions you can see the function here https://github.com/bitnami/bitnami-docker-laravel/blob/master/8/debian-10/rootfs/app-entrypoint.sh#L47-L62

**Comment by RokSiEu** [comment]
@dani8art thank you, then it looks like only log messages are still using mariadb and my error #97 lies somewhere else

**Comment by dani8art** [comment]
Yes you are right, `log "Connecting to mariadb at $db_address"` is still logging mariadb but the address is correct. What I can see in your logs is that your application is not authenticating properly against MySQL, is it?

**Pull request merged**
