### PR TITLE
PHP updated to 8.1.1

### LINKED ISSUE #147: PHP 8 support
https://github.com/bitnami/bitnami-docker-laravel/blob/c7e036f98408080f5aff2d6c08d5078f2e1b0d13/8/debian-10/Dockerfile#L12

Can we get another option for Laravel 8 with PHP 8? Currently using `docker.io/bitnami/laravel:8`

### PR DESCRIPTION
**Pull request by llabbasmkhll**
**Description of the change**

PHP version changed from 7 to 8   

**Benefits**

obviously PHP 8 has a huge performance and security Improvements like jit witch is faster than the old compiler .
for more information visit this post by kinsta 
[https://kinsta.com/blog/php-8/](https://kinsta.com/blog/php-8/)  

**Possible drawbacks**

there will be no drawbacks because all laravel versions are compatible with PHP 8 ( basically any newer version )

**Applicable issues**

- Fixes #147 

**Additional information**

thanks for reviewing

### CODE REVIEW

**Comment by sabist** [comment]
Great job ! php 7.4 active support well end soon. I recommend maintainers to accept this PR

**Comment by randradas** [comment]
Thank you @llabbasmkhll! we are reviewing it internally, I'll be back.

**Comment by randradas** [comment]
Hello @llabbasmkhll we are aware of the situation with the PHP 7.4 active support so we think it is a good idea to upgrade to PHP 8. However since this is a major change we need to create an internal task to check and test the change before merging the PR.

**Comment by llabbasmkhll** [comment]
hello @BhanuKorthiwada . tanks for reviewing and your response . im already using my fork as a container for my projects and i hadn't any issues so far . i will notice you if i face any issues

**Comment by randradas** [comment]
umm that's is good to know, we will take it into account in order to create the internal task.

**Comment by carrodher** [comment]
I just updated the Dockerfile in order to use the latest version of PHP 8.1.

According to the [official doc for laravel 8.X](https://laravel.com/docs/8.x/deployment#server-requirements), the only requirement is
> PHP >= 7.3
so it should be fine

**Pull request merged**
