### PR TITLE
Update setup.sh

### PR DESCRIPTION
**Pull request by 1ocate**
**Description of the change**

**Mac docker-Desktop** have issue when mount from host directory access slow  https://github.com/docker/for-mac/issues/3677

For me, this container from start until end take time 5-6 minutes.

Finally I found make slow command is in "opt/bitnami/scripts/laravel/setup.sh"
last line **chown -R bitnami:bitnami /app**

This command make cpu high my MAC.
maybe relection mac docker issue "https://github.com/docker/for-mac/issues/3677"
I suggest change that code 
**find /app ! -user bitnami -and ! -group bitnami -exec chown bitnami.bitnami {} \;**

so if add or update file, only that file will be change ownership. 

**Benefits**

before (not change) see takes time.
**chown -R bitnami:bitnami /app**
Screen Shot 2022-01-24 at 3 47 14 PM

After change

Screen Shot 2022-01-24 at 4 44 05 PM

**Applicable issues**

Relection with this issue #156

### CODE REVIEW

**Comment by Mauraza** [comment]
Hi @1ocate,

this is a change for a very specific change. Did you try to use `:cached` or `:delegated`? 
Maybe this guide helps you: https://www.docker.com/blog/user-guided-caching-in-docker-for-mac/

**Comment by 1ocate** [comment]
hi @Mauraza 

I just try :cached and :delegate.

This is result

use :cached
Screen Shot 2022-01-24 at 7 56 44 PM


use :delegated
Screen Shot 2022-01-24 at 8 07 29 PM

**Comment by Mauraza** [comment]
Hi @1ocate,

sorry, there is not much change, but we cannot accept this PR as it is only a docker-for-mac problem.

**Comment by 1ocate** [comment]
Hi @Mauraza 
No problem. 
I just want to notice about issue and that change for me start docker more then 1-2 minutes save.

I hope help this who using docker from Mac.

Thank you.

**Comment by Mauraza** [comment]
Hi @1ocate,

I'm sure that some users will find it useful, thanks!

**Pull request closed without merging**
