### PR TITLE
Run myapp container in privileged mode

### PR DESCRIPTION
**Pull request by LSaraguA**
Windows may require myapp container to run in privileged mode to avoid Operation not permitted when preserving times (V. #102)

**Description of the change**

Added property to run myapp container in privileged mode

**Benefits**

Frictionless starting container under Windows

**Possible drawbacks**

Unknown

**Applicable issues**

#102

**Additional information**

N/A

### CODE REVIEW

**Comment by andresbono** [comment]
Hi @LSaraguA, thanks for submitting the PR.

Running your containers as _privileged_ may not be the best option in terms of security. In the case of Laravel, most of the usage is for development only and shouldn't be an issue but even so, adding `privileged: true` in the docker-compose is a pattern that we would like to avoid.

What do you think about adding `privileged: false` to the `docker-compose` and adding a note in the README that explains the cases in which the users should change it to true for Windows?

cc @tompizmor, @juan131, @carrodher.

**Comment by LSaraguA** [comment]
Hi @andresbono,

I think it's reasonable to avoid privileged mode and your proposal sounds good to me.

Let's see what people CC'ed have to say,

**Comment by juan131** [comment]
I agree with @andresbono 
Running containers as *privileged* should not be the default behaviour but an exception instead.

**Comment by andresbono** [comment]
Thanks for the contribution, @LSaraguA!!

**Pull request merged**
