### PR TITLE
compose: removed `tty: true` from the compose spec

### PR DESCRIPTION
**Pull request by sameersbn**
https://github.com/docker/compose/issues/3633

### CODE REVIEW

**Comment by alexandernst** [comment]
Doesn't laravel require interactive mode? Did you test this @sameersbn ?

**Comment by sameersbn** [comment]
@alexandernst my limited tests do indicate that it works without any issues. It would be great if there's any particular case that your like to test against this PR.

**Comment by migmartri** [comment]
@alexandernst @sameersbn, initially I added `tty: true` in the rails docker-compose setup so you can use breakpoints (pry, etc) and then attach to the container for debugging.

I'd prefer to leave it in at least in the rails one.

**Comment by alexandernst** [comment]
I'm not sure if Laravel (or Elixir, Node/Gulp) would require tty for something. No real experience with Laravel. Let me ask and comment back.

**Pull request closed without merging**
